name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd photoalbum
          python manage.py test

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: |
          echo "${{ secrets.RAILWAY_TOKEN }}" | railway login
          
          # PORT változó beállítása
          railway variables set PORT=8000
          
          # Alkalmazás deployolása
          railway up --detach
          
          # Várakozás a deployment befejezésére
          sleep 30
          
          # Public networking engedélyezése a 8000-es porton
          railway service network public --port 8000
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}